### ISSUE TITLE
seccomp lab step order

### ISSUE THREAD

**Issue by mschuchard** [docker/labs#108]
I feel fairly certain that `Seccomp and Docker` under `Prerequisites` and `Clone the labs GitHub repo` as `Step 1` should be switched in the seccomp lab, but wanted to do this as an issue just in case I am wrong.

Also

> The remaining steps in this lab will assume that you are running commands from this `dockercon-workshop/seccomp` directory.

should be

> The remaining steps in this lab will assume that you are running commands from this `labs/security/seccomp` directory.

Although speaking of the `dockercon-workshop` git repo, you might want to put a `git clone` command for it in Step 5 of the apparmor lab. I realized when it mentioned to be in a `dockercon-workshop` directory I probably needed to search github for a repo with that name and clone it, but it might be helpful for others if it was more clear.

**Comment by ManoMarks** [comment]
@riyazdf can you review?

**Comment by riyazdf** [comment]
@mschuchard - you're right that the command will fail in the `Docker and Seccomp` section will fail if you run it because `default.json` won't exist.  That said, I don't think we need to reference that file since that section is mostly about an introduction about how docker uses seccomp, so I can generalize the filename.

Also, great catch on the directory - this lab was ported from github.com/riyazdf/dockercon-workshop so I missed some of the references.  I'll fix this.
