### ISSUE TITLE
standard_init_linux.go:187: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by videni** [docker/labs#336]
Run following commands in window10
```
docker pull videni/taoshouyou-docker
docker run -it -p 80:80 -v D:/test:/var/www videni/taoshouyou-docker    
```

will show this error:

>standard_init_linux.go:187: exec user process caused "no such file or directory"

**Comment by ManoMarks** [comment]
Since this isn't related to anything in the labs repo, I'm going to close this issue. 

If you're using Docker for Windows, I recommend posting here: https://github.com/docker/for-win.  

If you're using Docker Toolbox, I recommend posting the issue here: https://www.docker.com/products/docker-toolbox  

And you may also get debugging help in the [Docker Community Forums](https://forums.docker.com/)
